# Generated by Django 2.0.4 on 2018-05-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApacheS', '0003_typeproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('type_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApacheS.TypeProducts')),
            ],
        ),
    ]
