# Generated by Django 2.0.4 on 2018-05-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApacheS', '0007_company_location_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateField()),
                ('date_delivery', models.DateField()),
                ('amount', models.FloatField()),
                ('state', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('proof_of_payment', models.CharField(max_length=25)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApacheS.Department')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApacheS.Provider')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApacheS.Seller')),
            ],
        ),
    ]
