# Generated by Django 2.0.4 on 2018-05-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApacheS', '0009_client_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApacheS.Products')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApacheS.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='PurcharseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApacheS.Products')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApacheS.Purchase')),
            ],
        ),
    ]
